### ISSUE TITLE
Any idea why this build fails with "Unhandled 'error' event"?

### ISSUE THREAD

**Issue by dandv** [practicalmeteor/spacejam#36]
https://travis-ci.org/Wylio/meteor-mandrill/builds/71746610

```
$ node_modules/.bin/spacejam --mongo-url mongodb:// test-packages ./
spacejam: spawning meteor
spacejam: killing meteor
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
The command "node_modules/.bin/spacejam --mongo-url mongodb:// test-packages ./" exited with 8.
```

**Comment by dandv** [comment]
So the `meteor` executable wasn't found.

Turns out Travis moved to a container-based architecture, and Meteor needed sudo to write its launcher script.

[Adding `meteor` to $PATH fixed the problem](https://github.com/Wylio/meteor-mandrill/commit/b3086b5157fb8c7fcc7ff0f03123f7339787dde1).

Would be nice if spacejam gave a more explicit error message for `meteor` not being found.
