### ISSUE TITLE
Is there some way to prevent meteor auto-restart?

### ISSUE THREAD

**Issue by meonkeys** [practicalmeteor/spacejam#44]
I've got a situation where my Meteor package causes the tinytest Meteor app to crash the first time `Exited with code: 8`, but restarts and then works normally. This is caused by a failing db migration. After restarting, a "migrations locked" error is printed and the other tinytests succeed.

Is there some way to get spacejam to make sure Meteor does _not_ restart?

Here's a simple repro. Create a Meteor package with this code:

``` javascript
Meteor.startup(function() {
  const fs = Npm.require('fs');
  if (!fs.existsSync('/tmp/failFlagFile')) {
    const fd = fs.openSync('/tmp/failFlagFile', 'w');
    fs.closeSync(fd);
    WILL_CRASH_HERE
  }
});
```

The crash only happens the first time. After restarting, it'll skip the block with the offending code. Example output:

```
node_modules/.bin/spacejam test-packages ./
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
I20151109-13:21:20.615(-8)? test-in-console listening
W20151109-13:21:20.616(-8)? (STDERR) 
W20151109-13:21:20.617(-8)? (STDERR) /home/adamm/.meteor/packages/meteor-tool/.1.1.10.16mo0i3++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151109-13:21:20.617(-8)? (STDERR)                        throw(ex);
W20151109-13:21:20.617(-8)? (STDERR)                              ^
W20151109-13:21:20.617(-8)? (STDERR) ReferenceError: WILL_CRASH_HERE is not defined
W20151109-13:21:20.617(-8)? (STDERR)     at Package (spacejam-startup-repro.js:6:5)
W20151109-13:21:20.617(-8)? (STDERR)     at /tmp/meteor-test-runtbda1u/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
I20151109-13:21:22.952(-8)? test-in-console listening
=> Meteor server restarted
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
phantomjs: Running tests at http://localhost:4096/local using test-in-console
ReferenceError: Can't find variable: Npm

  http://localhost:4096/packages/spacejam-startup-repro.js?6b3d78d22f812eab7d3f31026b197aef25e437d4:31
  http://localhost:4096/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:777
  http://localhost:4096/packages/meteor.js?9730f4ff059088b3f7f14c0672d155218a1802d4:779
S: tinytest - example : OK
C: tinytest - example : OK
passed/expected/failed/total 2 / 0 / 0 / 2
##_meteor_magic##state: done
spacejam: phantomjs exited with code: 0
spacejam: killing meteor
```

**Comment by rbabayoff** [comment]
To figure out meteor is crashing, spacejam is waiting for the "Your application is crashing, waiting for file change" message meteor generates after a few restart attempts. See [here](https://github.com/practicalmeteor/spacejam/blob/eca8d6eb0b0c242373ac89fcb3fa5fdbf2a1776f/src/Meteor.coffee#L31). The output to wait on is actually configurable and can be provided on the command line, so you can just wait for "Exited with code: 8" instead:

```
spacejam test-packages --meteor-error-text="Exited with code: 8" ./
```

Let me know if this works for you.

**Comment by meonkeys** [comment]
Doesn't work for me.

```
$ node_modules/.bin/spacejam test-packages --meteor-error-text="Exited with code: 8" ./
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
I20151112-14:46:15.498(-8)? test-in-console listening
W20151112-14:46:15.500(-8)? (STDERR) 
W20151112-14:46:15.500(-8)? (STDERR) /home/adamm/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151112-14:46:15.500(-8)? (STDERR) 						throw(ex);
W20151112-14:46:15.500(-8)? (STDERR) 						      ^
W20151112-14:46:15.500(-8)? (STDERR) ReferenceError: WILL_CRASH_HERE is not defined
W20151112-14:46:15.500(-8)? (STDERR)     at Package (spacejam-startup-repro.js:7:5)
W20151112-14:46:15.500(-8)? (STDERR)     at /tmp/meteor-test-run18rnbw6/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
I20151112-14:46:17.727(-8)? test-in-console listening
=> Meteor server restarted
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
phantomjs: Running tests at http://localhost:4096/local using test-in-console
S: tinytest - example : OK
passed/expected/failed/total 1 / 0 / 0 / 1
##_meteor_magic##state: done
spacejam: phantomjs exited with code: 0
spacejam: killing meteor
spacejam: All tests have passed. Exiting.
$
```

BTW, one fix to my repro above, make sure `spacejam-startup-repro.js` and `spacejam-startup-repro-tests.js` are only loaded server-side. Here's my `package.js` file:

```javascript
Package.describe({
  name: 'spacejam-startup-repro',
  version: '0.0.1',
  // Brief, one-line summary of the package.
  summary: '',
  // URL to the Git repository containing the source code for this package.
  git: '',
  // By default, Meteor will default to using README.md for documentation.
  // To avoid submitting documentation, set this field to null.
  documentation: 'README.md'
});

Package.onUse(function(api) {
  api.versionsFrom('1.2.1');
  api.use('ecmascript');
  api.addFiles('spacejam-startup-repro.js', 'server'); // ADDED 'server' HERE
});

Package.onTest(function(api) {
  api.use('ecmascript');
  api.use('tinytest');
  api.use('spacejam-startup-repro');
  api.addFiles('spacejam-startup-repro-tests.js', 'server'); // ADDED 'server' HERE
});
```
