### ISSUE TITLE
Running `spacejam test-packages --driver-package=practicalmeteor:mocha-console-runner ./` fails

### ISSUE THREAD

**Issue by thiagodelgado111** [practicalmeteor/spacejam#63]
### System info:
ProductName:	Mac OS X
ProductVersion:	10.11.5

Node v5.5

### Details
```
=> Meteor server restarted
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: killing meteor
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at Phantomjs.run (/usr/local/lib/node_modules/spacejam/lib/Phantomjs.js:77:33)
    at Phantomjs.run (/usr/local/lib/node_modules/spacejam/lib/Phantomjs.js:4:61)
    at Spacejam.runPhantom (/usr/local/lib/node_modules/spacejam/lib/Spacejam.js:180:29)
    at Meteor.<anonymous> (/usr/local/lib/node_modules/spacejam/lib/Spacejam.js:115:24)
    at emitNone (events.js:86:13)
    at Meteor.emit (events.js:185:7)
    at Meteor.hasReadyText (/usr/local/lib/node_modules/spacejam/lib/Meteor.js:226:21)
    at Meteor.hasReadyText (/usr/local/lib/node_modules/spacejam/lib/Meteor.js:4:61)
```

**Comment by jsep** [comment]
Hello @thiagodelgado111 are you using the latest version of `spacejam` ?

**Comment by thiagodelgado111** [comment]
Hey @jsep, I npm installed it globally, is that right?

**Comment by jsep** [comment]
Yes you just have to run:

`npm install -g spacejam`

Today I'm going to release a new version, I'll let you know.

**Comment by thiagodelgado111** [comment]
Ok, @jsep! Will wait for it :) If there is anything I can help with, pls ping me :)

**Comment by jsep** [comment]
@thiagodelgado111 try this and let me know if it solve this issue:

`npm install -g spacejam@rc`

**Comment by thiagodelgado111** [comment]
Hey @jsep, thanks for helping! :) I've tried it again with the rc version and now I got a different error:
```
spacejam test-packages --driver-package=practicalmeteor:mocha-console-runner ./

spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
spacejam: meteor mongodb is ready
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
spacejam: spawning phantomjs
spacejam: killing meteor
spacejam: killing phantomjs
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

**Comment by serut** [comment]
Hey ! Can you execute your command with verbose ? `--loglevel debug`

**Comment by thiagodelgado111** [comment]
Here is the output:
```
Spacejam.constructor()
CLI.constructor()
CLI.exec()
command: test-packages
CLI.exec() options: { 'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  packages: [ './' ],
  command: 'test-packages' }
Spacejam.testPackages() { 'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  packages: [ './' ],
  command: 'test-packages' }
{ 'phantomjs-script': 'phantomjs-test-in-console.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  packages: [ './' ],
  command: 'test-packages' }
Meteor.runTestCommand() { '0': 'test-packages',
  '1':
   { 'phantomjs-script': 'phantomjs-test-in-console.js',
     'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
     'driver-package': 'practicalmeteor:mocha-console-runner',
     loglevel: 'debug',
     packages: [ './' ],
     command: 'test-packages' } }
meteor options: { dir: '.',
  port: 4096,
  packages: [ './' ],
  'driver-package': 'practicalmeteor:mocha-console-runner',
  'meteor-ready-text': '=> App running at:',
  'meteor-error-text': 'Waiting for file change.',
  'phantomjs-script': 'phantomjs-test-in-console.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'debug',
  command: 'test-packages' }
meteor cwd=/Users/thiagodelgado/Documents/code/provider
Meteor.getTestArgs() { dir: '.',
  port: 4096,
  packages: [ './' ],
  'driver-package': 'practicalmeteor:mocha-console-runner',
  'meteor-ready-text': '=> App running at:',
  'meteor-error-text': 'Waiting for file change.',
  'phantomjs-script': 'phantomjs-test-in-console.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'debug',
  command: 'test-packages' }
Meteor._globPackages() { '0': [ './' ] }
meteor args= [ 'test-packages',
  '--driver-package',
  'practicalmeteor:mocha-console-runner',
  '--port',
  4096,
  './' ]
ChildProcess.constructor()
ChildProcess.spawn() meteor [ 'test-packages',
  '--driver-package',
  'practicalmeteor:mocha-console-runner',
  '--port',
  4096,
  './' ]
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
MeteorMongodb.constructor() { '0': 24006 }
MeteorMongodb.findAllChildren() {}
@meteorPid 24006
spacejam: meteor mongodb is ready
Found meteor mongod child with pid:  24025
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
Spacejam.runPhantom()
Phantomjs.run() { '0': 'http://localhost:4096/local',
  '1': '--load-images=no --ssl-protocol=TLSv1',
  '2': 'phantomjs-test-in-console.js',
  '3': undefined,
  '4': undefined,
  '5': false }
script=/usr/local/lib/node_modules/spacejam/lib/phantomjs-test-in-console.js
spawnArgs: [ '--load-images=no',
  '--ssl-protocol=TLSv1',
  'phantomjs-test-in-console.js' ]
spawnOptions: { cwd: '/usr/local/lib/node_modules/spacejam/lib',
  detached: false,
  env:
   { TERM_SESSION_ID: 'w0t3p1:49D9136D-8A03-4FCB-AB9B-AA20DB214100',
     Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.js5n6hVCd6/Render',
     COLORFGBG: '7;0',
     ITERM_PROFILE: 'Default',
     XPC_FLAGS: '0x0',
     PWD: '/code/provider',
     SHELL: '/usr/local/bin/zsh',
     LC_CTYPE: 'UTF-8',
     TERM_PROGRAM_VERSION: '3.0.4',
     TERM_PROGRAM: 'iTerm.app',
     DISPLAY: '/private/tmp/com.apple.launchd.ju4hMt3RpF/org.macosforge.xquartz:0',
     TERM: 'xterm-256color',
     HOME: '/Users/thiagodelgado',
     TMPDIR: '/var/folders/l6/wmv1xmws59g_bdqlgntb30mh0000gn/T/',
     USER: 'thiagodelgado',
     XPC_SERVICE_NAME: '0',
     LOGNAME: 'thiagodelgado',
     ITERM_SESSION_ID: 'w0t3p1:49D9136D-8A03-4FCB-AB9B-AA20DB214100',
     __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
     SHLVL: '1',
     OLDPWD: '/code',
     NVM_DIR: '/Users/thiagodelgado/.nvm',
     NVM_CD_FLAGS: '-q',
     NVM_NODEJS_ORG_MIRROR: 'https://nodejs.org/dist',
     NVM_IOJS_ORG_MIRROR: 'https://iojs.org/dist',
     NVM_RC_VERSION: '',
     ZSH: '/Users/thiagodelgado/.oh-my-zsh',
     PAGER: 'less',
     LESS: '-R',
     LSCOLORS: 'Gxfxcxdxbxegedabagacad',
     MANPATH: '/Users/thiagodelgado/.nvm/versions/node/v5.5.0/share/man:/usr/local/share/man:/usr/share/man:/opt/X11/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man',
     NVM_PATH: '/Users/thiagodelgado/.nvm/versions/node/v5.5.0/lib/node',
     NVM_BIN: '/Users/thiagodelgado/.nvm/versions/node/v5.5.0/bin',
     _: '/usr/local/bin/spacejam',
     ROOT_URL: 'http://localhost:4096/local' } }
ChildProcess.constructor()
ChildProcess.spawn() phantomjs [ '--load-images=no',
  '--ssl-protocol=TLSv1',
  'phantomjs-test-in-console.js' ]
spacejam: spawning phantomjs
ChildProcess.process.on 'exit': @command=meteor @killed=false code=1
ChildProcess.kill() signal=SIGTERM @command=meteor @killed=false
spacejam: killing meteor
MeteorMongodb.process.on 'exit': code=1
MeteorMongodb.kill() killed= false
ChildProcess.process.on 'exit': @command=phantomjs @killed=false code=1
ChildProcess.kill() signal=SIGTERM @command=phantomjs @killed=false
spacejam: killing phantomjs
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn phantomjs ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

**Comment by serut** [comment]
`phantomjs` fails to spawn, it can be an error related to node `v5.5.0`.   
I see that you use nvm, can you try spacejam with node 0.10.43 ? (~ `nvm install 0.10.43 && nvm use 0.10.43`)

**Comment by rbabayoff** [comment]
@thiagodelgado111 , as @serut suggested, please use node 0.10.43, which is what we use with spacejam, since it's the same one latest version of meteor will use. I think we should force a node version limitation in package.json, going forward.

**Comment by thiagodelgado111** [comment]
Hey @serut, @rbabayoff, thanks a lot for helping! It's a shame I didn't realised that before, sorry about that. Unfortunately, it's still failing for me even after reinstalling spacejam using the correct node version, here follows the log I get from it:

```
8:43:25 › nvm ls
->     v0.10.43
         v5.5.0
         v6.2.0
         system
default -> 0.10.43 (-> v0.10.43)
node -> v5.5 (-> v5.5.0)
system -> 5.5.0 (-> v5.5.0)
stable -> 6.2 (-> v6.2.0) (default)
iojs -> N/A (default)

8:43:41 › spacejam test-packages --driver-package=practicalmeteor:mocha-console-runner --loglevel debug ./
Spacejam.constructor()
CLI.constructor()
CLI.exec()
command: test-packages
CLI.exec() options: { 'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  packages: [ './' ],
  command: 'test-packages' }
Spacejam.testPackages() { 'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  packages: [ './' ],
  command: 'test-packages' }
{ 'phantomjs-script': 'phantomjs-test-in-console.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  'driver-package': 'practicalmeteor:mocha-console-runner',
  loglevel: 'debug',
  packages: [ './' ],
  command: 'test-packages' }
Meteor.runTestCommand() { '0': 'test-packages',
  '1':
   { 'phantomjs-script': 'phantomjs-test-in-console.js',
     'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
     'driver-package': 'practicalmeteor:mocha-console-runner',
     loglevel: 'debug',
     packages: [ './' ],
     command: 'test-packages' } }
meteor options: { dir: '.',
  port: 4096,
  packages: [ './' ],
  'driver-package': 'practicalmeteor:mocha-console-runner',
  'meteor-ready-text': '=> App running at:',
  'meteor-error-text': 'Waiting for file change.',
  'phantomjs-script': 'phantomjs-test-in-console.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'debug',
  command: 'test-packages' }
meteor cwd=/Users/thiagodelgado/Documents/code/provider
Meteor.getTestArgs() { dir: '.',
  port: 4096,
  packages: [ './' ],
  'driver-package': 'practicalmeteor:mocha-console-runner',
  'meteor-ready-text': '=> App running at:',
  'meteor-error-text': 'Waiting for file change.',
  'phantomjs-script': 'phantomjs-test-in-console.js',
  'phantomjs-options': '--load-images=no --ssl-protocol=TLSv1',
  loglevel: 'debug',
  command: 'test-packages' }
Meteor._globPackages() { '0': [ './' ] }
meteor args= [ 'test-packages',
  '--driver-package',
  'practicalmeteor:mocha-console-runner',
  '--port',
  4096,
  './' ]
ChildProcess.constructor()
ChildProcess.spawn() meteor [ 'test-packages',
  '--driver-package',
  'practicalmeteor:mocha-console-runner',
  '--port',
  4096,
  './' ]
spacejam: spawning meteor
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
MeteorMongodb.constructor() { '0': 2478 }
MeteorMongodb.findAllChildren() {}
@meteorPid 2478
spacejam: meteor mongodb is ready
Found meteor mongod child with pid:  2497
=> Started your app.

=> App running at: http://localhost:4096/
spacejam: meteor is ready
Spacejam.runPhantom()
Phantomjs.run() { '0': 'http://localhost:4096/local',
  '1': '--load-images=no --ssl-protocol=TLSv1',
  '2': 'phantomjs-test-in-console.js',
  '3': undefined,
  '4': undefined,
  '5': false }
script=/usr/local/lib/node_modules/spacejam/lib/phantomjs-test-in-console.js
spawnArgs: [ '--load-images=no',
  '--ssl-protocol=TLSv1',
  'phantomjs-test-in-console.js' ]
spawnOptions: { cwd: '/usr/local/lib/node_modules/spacejam/lib',
  detached: false,
  env:
   { TERM_SESSION_ID: 'w0t1p0:C00F7167-F424-41C7-85D4-61FC63074184',
     SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.ecmsrWGIZ6/Listeners',
     Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.r005F7fB3Y/Render',
     COLORFGBG: '7;0',
     ITERM_PROFILE: 'Default',
     XPC_FLAGS: '0x0',
     PWD: '/code/provider',
     SHELL: '/usr/local/bin/zsh',
     SECURITYSESSIONID: '186a7',
     LC_CTYPE: 'UTF-8',
     TERM_PROGRAM_VERSION: '3.0.4',
     TERM_PROGRAM: 'iTerm.app',
     DISPLAY: '/private/tmp/com.apple.launchd.OksE5HcAVs/org.macosforge.xquartz:0',
     COMMAND_MODE: 'unix2003',
     TERM: 'xterm-256color',
     HOME: '/Users/thiagodelgado',
     TMPDIR: '/var/folders/l6/wmv1xmws59g_bdqlgntb30mh0000gn/T/',
     USER: 'thiagodelgado',
     XPC_SERVICE_NAME: '0',
     LOGNAME: 'thiagodelgado',
     __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
     ITERM_SESSION_ID: 'w0t1p0:C00F7167-F424-41C7-85D4-61FC63074184',
     SHLVL: '1',
     OLDPWD: '/Users/thiagodelgado/Documents/code/',
     NVM_DIR: '/Users/thiagodelgado/.nvm',
     NVM_CD_FLAGS: '-q',
     NVM_NODEJS_ORG_MIRROR: 'https://nodejs.org/dist',
     NVM_IOJS_ORG_MIRROR: 'https://iojs.org/dist',
     NVM_RC_VERSION: '',
     PAGER: 'less',
     LESS: '-R',
     LSCOLORS: 'Gxfxcxdxbxegedabagacad',
     NVM_PATH: '/Users/thiagodelgado/.nvm/v0.10.43/lib/node',
     NVM_BIN: '/Users/thiagodelgado/.nvm/v0.10.43/bin',
     _: '/usr/local/bin/spacejam',
     ROOT_URL: 'http://localhost:4096/local' } }
ChildProcess.constructor()
ChildProcess.spawn() phantomjs [ '--load-images=no',
  '--ssl-protocol=TLSv1',
  'phantomjs-test-in-console.js' ]
spacejam: spawning phantomjs
ChildProcess.process.on 'exit': @command=meteor @killed=false code=1
ChildProcess.kill() signal=SIGTERM @command=meteor @killed=false
spacejam: killing meteor
MeteorMongodb.process.on 'exit': code=1
MeteorMongodb.kill() killed= false
ChildProcess.process.on 'exit': @command=phantomjs @killed=false code=1
ChildProcess.kill() signal=SIGTERM @command=phantomjs @killed=false
spacejam: killing phantomjs

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

Any thoughts on that?

**Comment by thiagodelgado111** [comment]
Guys, testing latest spacejam version with Meteor 1.4.x is working for me now, so I'm closing this issue, thanks a bunch for your help! You're doing a great job! Thanks again!
